// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assemble_pairs
List assemble_pairs(IntegerMatrix nn_idx, NumericMatrix nn_dists, int nnk);
RcppExport SEXP _blockpairwise_assemble_pairs(SEXP nn_idxSEXP, SEXP nn_distsSEXP, SEXP nnkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nn_dists(nn_distsSEXP);
    Rcpp::traits::input_parameter< int >::type nnk(nnkSEXP);
    rcpp_result_gen = Rcpp::wrap(assemble_pairs(nn_idx, nn_dists, nnk));
    return rcpp_result_gen;
END_RCPP
}
// matern
double matern(double d, double phi, double nu);
RcppExport SEXP _blockpairwise_matern(SEXP dSEXP, SEXP phiSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(matern(d, phi, nu));
    return rcpp_result_gen;
END_RCPP
}
// prepare_bcl_storage
SEXP prepare_bcl_storage(Rcpp::List y_list_R,
                         Rcpp::List X_list_R,
                         Rcpp::List valid_pairs_list_R,
                         Rcpp::List dist_pairs_list_R);
RcppExport SEXP _blockpairwise_prepare_bcl_storage(SEXP y_list_RSEXP,
                                                   SEXP X_list_RSEXP,
                                                   SEXP valid_pairs_list_RSEXP,
                                                   SEXP dist_pairs_list_RSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< Rcpp::List >::type y_list_R(y_list_RSEXP);
  Rcpp::traits::input_parameter< Rcpp::List >::type X_list_R(X_list_RSEXP);
  Rcpp::traits::input_parameter< Rcpp::List >::type valid_pairs_list_R(valid_pairs_list_RSEXP);
  Rcpp::traits::input_parameter< Rcpp::List >::type dist_pairs_list_R(dist_pairs_list_RSEXP);
  rcpp_result_gen = Rcpp::wrap(prepare_bcl_storage(y_list_R, X_list_R,
                                                   valid_pairs_list_R,
                                                   dist_pairs_list_R));
  return rcpp_result_gen;
  END_RCPP
}
// bcl_gaussian_marginal_ptr
double bcl_gaussian_marginal_ptr(SEXP ptr_, double mu, double sigma2, double phi, double t, double t2, double nu);
RcppExport SEXP _blockpairwise_bcl_gaussian_marginal_ptr(SEXP ptr_SEXP, SEXP muSEXP, SEXP sigma2SEXP, SEXP phiSEXP, SEXP tSEXP, SEXP t2SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr_(ptr_SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(bcl_gaussian_marginal_ptr(ptr_, mu, sigma2, phi, t, t2, nu));
    return rcpp_result_gen;
END_RCPP
}
// bcl_gaussian_conditional_ptr
double bcl_gaussian_conditional_ptr(SEXP ptr_, double mu, double sigma2, double phi, double t, double t2, double nu);
RcppExport SEXP _blockpairwise_bcl_gaussian_conditional_ptr(SEXP ptr_SEXP, SEXP muSEXP, SEXP sigma2SEXP, SEXP phiSEXP, SEXP tSEXP, SEXP t2SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr_(ptr_SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(bcl_gaussian_conditional_ptr(ptr_, mu, sigma2, phi, t, t2, nu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blockpairwise_assemble_pairs", (DL_FUNC) &_blockpairwise_assemble_pairs, 3},
    {"_blockpairwise_matern", (DL_FUNC) &_blockpairwise_matern, 3},
    {"_blockpairwise_prepare_bcl_storage", (DL_FUNC) &_blockpairwise_prepare_bcl_storage, 3},
    {"_blockpairwise_bcl_gaussian_marginal_ptr", (DL_FUNC) &_blockpairwise_bcl_gaussian_marginal_ptr, 7},
    {"_blockpairwise_bcl_gaussian_conditional_ptr", (DL_FUNC) &_blockpairwise_bcl_gaussian_conditional_ptr, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_blockpairwise(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
