// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assemble_pairs
List assemble_pairs(IntegerMatrix nn_idx, NumericMatrix nn_dists, int nnk);
RcppExport SEXP _blockpairwise_assemble_pairs(SEXP nn_idxSEXP, SEXP nn_distsSEXP, SEXP nnkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nn_dists(nn_distsSEXP);
    Rcpp::traits::input_parameter< int >::type nnk(nnkSEXP);
    rcpp_result_gen = Rcpp::wrap(assemble_pairs(nn_idx, nn_dists, nnk));
    return rcpp_result_gen;
END_RCPP
}
// matern
double matern(double d, double range, double smooth);
RcppExport SEXP _blockpairwise_matern(SEXP dSEXP, SEXP rangeSEXP, SEXP smoothSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type smooth(smoothSEXP);
    rcpp_result_gen = Rcpp::wrap(matern(d, range, smooth));
    return rcpp_result_gen;
END_RCPP
}
// prepare_bcl_storage
SEXP prepare_bcl_storage(Rcpp::List y_list_R, Rcpp::List X_list_R, Rcpp::List valid_pairs_list_R, Rcpp::List dist_pairs_list_R);
RcppExport SEXP _blockpairwise_prepare_bcl_storage(SEXP y_list_RSEXP, SEXP X_list_RSEXP, SEXP valid_pairs_list_RSEXP, SEXP dist_pairs_list_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type y_list_R(y_list_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type X_list_R(X_list_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type valid_pairs_list_R(valid_pairs_list_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type dist_pairs_list_R(dist_pairs_list_RSEXP);
    rcpp_result_gen = Rcpp::wrap(prepare_bcl_storage(y_list_R, X_list_R, valid_pairs_list_R, dist_pairs_list_R));
    return rcpp_result_gen;
END_RCPP
}
// bcl_gaussian_marginal_ptr
double bcl_gaussian_marginal_ptr(SEXP ptr_, Rcpp::NumericVector beta, double sill, double range, double t, double t2, double smooth, int nthreads, int min_pairs_parallel);
RcppExport SEXP _blockpairwise_bcl_gaussian_marginal_ptr(SEXP ptr_SEXP, SEXP betaSEXP, SEXP sillSEXP, SEXP rangeSEXP, SEXP tSEXP, SEXP t2SEXP, SEXP smoothSEXP, SEXP nthreadsSEXP, SEXP min_pairs_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr_(ptr_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sill(sillSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type min_pairs_parallel(min_pairs_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(bcl_gaussian_marginal_ptr(ptr_, beta, sill, range, t, t2, smooth, nthreads, min_pairs_parallel));
    return rcpp_result_gen;
END_RCPP
}
// bcl_gaussian_conditional_ptr
double bcl_gaussian_conditional_ptr(SEXP ptr_, Rcpp::NumericVector beta, double sill, double range, double t, double t2, double smooth, int nthreads, int min_pairs_parallel);
RcppExport SEXP _blockpairwise_bcl_gaussian_conditional_ptr(SEXP ptr_SEXP, SEXP betaSEXP, SEXP sillSEXP, SEXP rangeSEXP, SEXP tSEXP, SEXP t2SEXP, SEXP smoothSEXP, SEXP nthreadsSEXP, SEXP min_pairs_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr_(ptr_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sill(sillSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type min_pairs_parallel(min_pairs_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(bcl_gaussian_conditional_ptr(ptr_, beta, sill, range, t, t2, smooth, nthreads, min_pairs_parallel));
    return rcpp_result_gen;
END_RCPP
}
// prepare_zi_storage_cpp
SEXP prepare_zi_storage_cpp(List y_list, List pairs_list, List dist_list, Nullable<List> X_list, Nullable<List> W_list, bool has_X, bool has_W);
RcppExport SEXP _blockpairwise_prepare_zi_storage_cpp(SEXP y_listSEXP, SEXP pairs_listSEXP, SEXP dist_listSEXP, SEXP X_listSEXP, SEXP W_listSEXP, SEXP has_XSEXP, SEXP has_WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< List >::type pairs_list(pairs_listSEXP);
    Rcpp::traits::input_parameter< List >::type dist_list(dist_listSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type W_list(W_listSEXP);
    Rcpp::traits::input_parameter< bool >::type has_X(has_XSEXP);
    Rcpp::traits::input_parameter< bool >::type has_W(has_WSEXP);
    rcpp_result_gen = Rcpp::wrap(prepare_zi_storage_cpp(y_list, pairs_list, dist_list, X_list, W_list, has_X, has_W));
    return rcpp_result_gen;
END_RCPP
}
// bp_zi_weibull_ptr
double bp_zi_weibull_ptr(SEXP ptr_, NumericVector par, bool has_X, bool has_W, double eps, int nthreads, int min_pairs_parallel);
RcppExport SEXP _blockpairwise_bp_zi_weibull_ptr(SEXP ptr_SEXP, SEXP parSEXP, SEXP has_XSEXP, SEXP has_WSEXP, SEXP epsSEXP, SEXP nthreadsSEXP, SEXP min_pairs_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr_(ptr_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< bool >::type has_X(has_XSEXP);
    Rcpp::traits::input_parameter< bool >::type has_W(has_WSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type min_pairs_parallel(min_pairs_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(bp_zi_weibull_ptr(ptr_, par, has_X, has_W, eps, nthreads, min_pairs_parallel));
    return rcpp_result_gen;
END_RCPP
}
// bp_zi_weibull_cpp
double bp_zi_weibull_cpp(const NumericVector& par, const List& y_list, const List& pairs_list, const List& dist_list, const Nullable<List>& X_list, const Nullable<List>& W_list, const bool has_X, const bool has_W, const double eps, const int nthreads, const int min_pairs_parallel);
RcppExport SEXP _blockpairwise_bp_zi_weibull_cpp(SEXP parSEXP, SEXP y_listSEXP, SEXP pairs_listSEXP, SEXP dist_listSEXP, SEXP X_listSEXP, SEXP W_listSEXP, SEXP has_XSEXP, SEXP has_WSEXP, SEXP epsSEXP, SEXP nthreadsSEXP, SEXP min_pairs_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type pairs_list(pairs_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type dist_list(dist_listSEXP);
    Rcpp::traits::input_parameter< const Nullable<List>& >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< const Nullable<List>& >::type W_list(W_listSEXP);
    Rcpp::traits::input_parameter< const bool >::type has_X(has_XSEXP);
    Rcpp::traits::input_parameter< const bool >::type has_W(has_WSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const int >::type min_pairs_parallel(min_pairs_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(bp_zi_weibull_cpp(par, y_list, pairs_list, dist_list, X_list, W_list, has_X, has_W, eps, nthreads, min_pairs_parallel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blockpairwise_assemble_pairs", (DL_FUNC) &_blockpairwise_assemble_pairs, 3},
    {"_blockpairwise_matern", (DL_FUNC) &_blockpairwise_matern, 3},
    {"_blockpairwise_prepare_bcl_storage", (DL_FUNC) &_blockpairwise_prepare_bcl_storage, 4},
    {"_blockpairwise_bcl_gaussian_marginal_ptr", (DL_FUNC) &_blockpairwise_bcl_gaussian_marginal_ptr, 9},
    {"_blockpairwise_bcl_gaussian_conditional_ptr", (DL_FUNC) &_blockpairwise_bcl_gaussian_conditional_ptr, 9},
    {"_blockpairwise_prepare_zi_storage_cpp", (DL_FUNC) &_blockpairwise_prepare_zi_storage_cpp, 7},
    {"_blockpairwise_bp_zi_weibull_ptr", (DL_FUNC) &_blockpairwise_bp_zi_weibull_ptr, 7},
    {"_blockpairwise_bp_zi_weibull_cpp", (DL_FUNC) &_blockpairwise_bp_zi_weibull_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_blockpairwise(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
