# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assemble_pairs <- function(nn_idx, nn_dists, nnk) {
    .Call(`_blockpairwise_assemble_pairs`, nn_idx, nn_dists, nnk)
}

matern <- function(d, phi, nu) {
    .Call(`_blockpairwise_matern`, d, phi, nu)
}

prepare_bcl_storage <- function(Z_list_R, valid_pairs_list_R, dist_pairs_list_R) {
    .Call(`_blockpairwise_prepare_bcl_storage`, Z_list_R, valid_pairs_list_R, dist_pairs_list_R)
}

bcl_gaussian_marginal_ptr <- function(ptr_, mu, sigma2, phi, t, t2, nu) {
    .Call(`_blockpairwise_bcl_gaussian_marginal_ptr`, ptr_, mu, sigma2, phi, t, t2, nu)
}

bcl_gaussian_conditional_ptr <- function(ptr_, mu, sigma2, phi, t, t2, nu) {
    .Call(`_blockpairwise_bcl_gaussian_conditional_ptr`, ptr_, mu, sigma2, phi, t, t2, nu)
}

